

rpn: 
  
  scales: [.5, 1, 2, .25, 1.5]
  aspect_ratios: [1]
  nms_threshold: 0.7
  image_input_size: 1024
  feature_map_size: 32
  feature_dim: 1024
  hidden_dim: 256

metrics:
  auroc:
    type: auroc
  prec_froc_fpr=point5:
    type: precision_froc
    fpr: .5
  prec_froc_fpr=point25:
    type: precision_froc
    fpr: .25
  prec_froc_fpr=1:
    type: precision_froc
    fpr: 1

freeze_chexnet: yes
lambda_: 10
num_training_examples_per_image: 64
min_num_positive_examples: 1
positivity_threshold: 0.5             # for selecting training examples
negativity_threshold: 0.05            # for selecting training examples
lr: 1e-4

metrics_match_threshold: 0.2
