
defaults:
  - _self_
  - data: default
  - trainer: default
  - model: default
  - machine: server
  - mode: default
  - metrics: default
  - optimizer: default

print_config: yes
disable_warnings: yes

